/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivemapRouteImport } from './routes/livemap'
import { Route as IndexRouteImport } from './routes/index'

const LivemapRoute = LivemapRouteImport.update({
  id: '/livemap',
  path: '/livemap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/livemap': typeof LivemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/livemap': typeof LivemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/livemap': typeof LivemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/livemap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/livemap'
  id: '__root__' | '/' | '/livemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LivemapRoute: typeof LivemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livemap': {
      id: '/livemap'
      path: '/livemap'
      fullPath: '/livemap'
      preLoaderRoute: typeof LivemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LivemapRoute: LivemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
